/*
 * Copyright (c) 2014. Real Time Genomics Limited.
 *
 * Use of this source code is bound by the Real Time Genomics Limited Software Licence Agreement
 * for Academic Non-commercial Research Purposes only.
 *
 * If you did not receive a license accompanying this file, a copy must first be obtained by email
 * from support@realtimegenomics.com.  On downloading, using and/or continuing to use this source
 * code you accept the terms of that license agreement and any amendments to those terms that may
 * be made from time to time by Real Time Genomics Limited.
 */
package com.rtg.variant.bayes.snp;

import com.rtg.util.StringUtils;
import com.rtg.variant.bayes.EvidenceAcceptor;
import com.rtg.variant.bayes.EvidenceInterface;

/**
 * Submits Evidence obtained from matching to an EvidenceAcceptor.
 * @param <D> Type of description that will be Generated by factories
 */
public class EvidenceMatcher<D extends EvidenceAcceptor> implements MatcherInterface {

  private final ReferenceBasedBuffer<D> mBuffer;
  private final CachedEvidenceFactory mCachedEvidenceFactory;

  /**
   * Construct a new evidence matcher.
   * @param buffer manages per-position <code>EvidenceAcceptor</code> s
   * @param evidenceFactory factory for retrieving cached evidence objects
   */
  public EvidenceMatcher(final ReferenceBasedBuffer<D> buffer, CachedEvidenceFactory evidenceFactory) {
    mBuffer = buffer;
    mCachedEvidenceFactory = evidenceFactory;
  }

  @Override
  public void match(int refPosition, int readBasesLeft, int readBasesRight, int readNt, int mapQ, int phred, int stateIndex) {
    if (readNt > 0) {
      final EvidenceInterface ev = mCachedEvidenceFactory.evidence(readNt - 1, readBasesLeft, readBasesRight, mapQ, phred, stateIndex, 0, false);
      match(refPosition, ev);
    }
  }

  @Override
  public void match(int refPosition, EvidenceInterface evid) {
    final D acceptor = mBuffer.get(refPosition);
    if (acceptor != null) {
      acceptor.increment(evid);
    }
  }

  @Override
  public void unmapped(int refPosition) {
    final EvidenceInterface ev = mCachedEvidenceFactory.evidence(0, 0, 0, 0, 0, 0, 0, true);
    match(refPosition, ev);
  }

  @Override
  public int getStateIndex(boolean isForward, boolean isReadPaired, boolean isFirst, boolean isMated) {
    return mCachedEvidenceFactory.getStateIndex(isForward, isReadPaired, isFirst, isMated);
  }

  /**
   * Return the EvidenceAcceptor for the current position and move to the next
   * position.
   *
   * @param ref position in reference
   * @return the <code>EvidenceAcceptor</code>
   */
  public D step(final int ref) {
    if (ref != mBuffer.base()) {
      throw new IllegalStateException("ref=" + ref + " != base=" + mBuffer.base());
    }
    return mBuffer.step();
  }

  @Override
  public String toString() {
    return "Matcher:" + StringUtils.LS + mBuffer;
  }
}
