/*
 * Copyright (c) 2014. Real Time Genomics Limited.
 *
 * Use of this source code is bound by the Real Time Genomics Limited Software Licence Agreement
 * for Academic Non-commercial Research Purposes only.
 *
 * If you did not receive a license accompanying this file, a copy must first be obtained by email
 * from support@realtimegenomics.com.  On downloading, using and/or continuing to use this source
 * code you accept the terms of that license agreement and any amendments to those terms that may
 * be made from time to time by Real Time Genomics Limited.
 */

package com.rtg.util;

import java.io.IOException;
import java.io.InputStream;

import com.rtg.util.store.StoreDirResource;
import com.rtg.util.store.StoreDirectory;

import junit.framework.TestCase;

/**
 */
public class MD5UtilsTest extends TestCase {

  //Long default buffer
  public void testLong() throws IOException {
    final StoreDirectory dir = new StoreDirResource("com/rtg/assembler/planning/resources");
    final InputStream is = dir.child("header.txt").inputStream();
    //taken from the manifest file which was generated by "md5 -r" on MacOSX
    assertEquals("762b36734794180251a4a46aefde8a68", MD5Utils.md5(is));
    is.close();
  }

  //Short buffer
  public void testShort() throws IOException {
    final StoreDirectory dir = new StoreDirResource("com/rtg/assembler/planning/resources");
    final InputStream is = dir.child("header.txt").inputStream();
    //taken from the manifest file which was generated by "md5 -r" on MacOSX
    assertEquals("762b36734794180251a4a46aefde8a68", MD5Utils.md5(is, 10));
    is.close();
  }

  public void testString() {
    assertEquals("bb1ce698abbc629090bfdb4961343bb4", MD5Utils.md5("fluffy bunnies are fluffy"));
  }
}
