/*
 * Copyright (c) 2014. Real Time Genomics Limited.
 *
 * Use of this source code is bound by the Real Time Genomics Limited Software Licence Agreement
 * for Academic Non-commercial Research Purposes only.
 *
 * If you did not receive a license accompanying this file, a copy must first be obtained by email
 * from support@realtimegenomics.com.  On downloading, using and/or continuing to use this source
 * code you accept the terms of that license agreement and any amendments to those terms that may
 * be made from time to time by Real Time Genomics Limited.
 */
package com.rtg.util;

import java.io.File;
import java.io.IOException;

import com.rtg.util.diagnostic.ErrorType;
import com.rtg.util.diagnostic.NoTalkbackSlimException;
import com.rtg.util.io.FileUtils;

/**
 * Helper class for HTML reports generated by our modules
 */
public class HtmlReportHelper {

  /** Suffix for a report dir */
  public static final String REPORT_DIR_SUFFIX = "_files";

  private final File mOutputDir;
  private final File mReportFile;
  private final File mResourcesDir;

  /**
   * Construct an <code>HtmlReportHelper</code>
   * @param outputDir the base output directory as specified by the user
   * @param reportName the base report name (e.g. "report") - omitting any file type suffix
   */
  public HtmlReportHelper(File outputDir, String reportName) {
    mOutputDir = outputDir;
    mReportFile = new File(outputDir, reportName + ".html");
    mResourcesDir = new File(outputDir, reportName + REPORT_DIR_SUFFIX);
  }

  /**
   * @return the <code>File</code> object to write the report to
   */
  public File getReportFile() {
    return mReportFile;
  }

  /**
   * @return the base dir
   */
  public File getBaseDir() {
    return mOutputDir;
  }

  /**
   * @return the name of the directory under the output directory which will contain resources for the report
   */
  public String getResourcesDirName() {
    return mResourcesDir.getName();
  }

  /**
   * Get the resources directory, creating it if it doesn't exist
   * @return the resources directory
   */
  public File getResourcesDir() {
    if (!mResourcesDir.exists() && !mResourcesDir.mkdir()) {
      throw new NoTalkbackSlimException(ErrorType.DIRECTORY_NOT_CREATED, mResourcesDir.getPath());
    }
    return mResourcesDir;
  }

  /**
   * Copy resources to the report directory. File names are retained.
   * Creates report files directory if necessary.
   * @param resources java resource paths which should be copied to the report directory
   * @throws IOException if an exception occurs during io
   */
  public void copyResources(String... resources) throws IOException {
    getResourcesDir();  //ensure resources dir exists
    for (String resource : resources) {
      final int lastSep = resource.lastIndexOf("/");
      final String fileName;
      if (lastSep == -1) {
        fileName = resource;
      } else {
        fileName = resource.substring(lastSep);
      }
      FileUtils.copyResource(resource, new File(mResourcesDir, fileName));
    }
  }
}
