/*
 * Copyright (c) 2014. Real Time Genomics Limited.
 *
 * Use of this source code is bound by the Real Time Genomics Limited Software Licence Agreement
 * for Academic Non-commercial Research Purposes only.
 *
 * If you did not receive a license accompanying this file, a copy must first be obtained by email
 * from support@realtimegenomics.com.  On downloading, using and/or continuing to use this source
 * code you accept the terms of that license agreement and any amendments to those terms that may
 * be made from time to time by Real Time Genomics Limited.
 */
package com.rtg.position.output;

/**
 * Common code used for output.
 */
public final class Utility {

  private Utility() { }  //prevent instantiation

  /**
   * Produce a string that formats an e-value as close as possible to
   * that generated by BLAST.
   * @param evalue to be formatted.
   * @return the formatted string.
   */
  public static String eFormat(final double evalue) {
    final String fmt;
    if (evalue < 1.0e-180) {
      return "0.0";
    }
    if (evalue < 1.0e-99) {
      fmt = "%1$2.0e"; //"%2.0le"
      final String str = String.format(fmt, evalue);
      return str.substring(1); /* Knock off digit. */
    }
    if (evalue < 0.0009) {
      fmt = "%1$3.0e"; //"%3.0le"
    } else if (evalue < 0.1) {
      fmt = "%1$4.3f"; //"%4.3lf"
    } else if (evalue < 1.0) {
      fmt = "%1$3.2f"; //"%3.2lf"
    } else if (evalue < 10.0) {
      fmt = "%1$2.1f"; //"%2.1lf"
    } else {
      fmt = "%1$1.0f"; //"%5.0lf"
    }
    return String.format(fmt, evalue);
  }

}
